#!/usr/bin/env python

import sys
sys.path.append("../..")
from src import parser
from src import cogen

if __name__ == "__main__":
    with open(sys.argv[1], 'r') as f:
        intcodes, vartable = parser.parse(f)
        asm = cogen.cogen(intcodes, vartable)

    # for svlist in vartable.svlists:
    #     sys.stderr.write(str(svlist))

    # for line in intcodes:
    #     sys.stderr.write(line["label"] + '\t' + line["code"] + "\t\tScope:" + str(line["scope"]))

    # sys.stderr.write("\n====Assembly====")
    for line in asm:
        print(line)
